# Generated by Django 5.0.6 on 2026-03-18 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labroom',
            name='capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
