# Generated by Django 5.0.6 on 2026-03-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_labroom_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='labroom',
            name='status',
            field=models.CharField(choices=[('Operational', 'Operational'), ('Maintenance', 'Maintenance')], default='Operational', max_length=20),
        ),
    ]
